apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres-product
          image: "postgres:{{ .Values.postgres.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.postgres.product.port }}
          envFrom:
            - secretRef:
                name: postgres-product-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: storage-product-pvc