apiVersion: batch/v1
kind: Job
metadata:
  name: apply-schema-product
  namespace: argo-kube-test
spec:
  template:
    spec:
      containers:
      - name: apply-schema
        image: "postgres:{{ .Values.postgres.version }}"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-product-secret 
              key: POSTGRES_PASSWORD
        command: ["/bin/sh", "-c"]
        args:
          - |
            DB_EXISTS=$(psql -h {{ .Release.Name }}-product -U {{ .Values.postgres.product.user }} -p {{ .Values.postgres.product.port }} -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='{{ .Values.postgres.product.dbName }}'")
            if [ -z "$DB_EXISTS" ]; then
              psql -h {{ .Release.Name }}-product -U {{ .Values.postgres.product.user }} -p {{ .Values.postgres.product.port }} -d postgres -c "CREATE DATABASE \"{{ .Values.postgres.product.dbName }}\""
            fi
            psql -h {{ .Release.Name }}-product -U {{ .Values.postgres.product.user }} -p {{ .Values.postgres.product.port }} -d {{ .Values.postgres.product.dbName }} -f /schema/schema.sql
        volumeMounts:
        - name: schema-volume
          mountPath: /schema
      restartPolicy: Never
      volumes:
      - name: schema-volume
        configMap:
          name: postgre-product-schema
  backoffLimit: 3
