apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-product
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: postgres-product
  ports:
    - name: db-port
      port: {{ .Values.postgres.product.port }}
      targetPort: 5432