postgres:
  version: "13.16"
  replicas: 2
  dbName: "Breizhsport"
  port: 5432
  user: "postgresUser"
  password: "1234"
  storage: "4Gi"
ingress:
  globalPort: 8080
express:
  replicas: 2
node: 
  version: "20-alpine"
  port: 3001
api:
  githubLink: "https://github.com/breizhsport-cube-3/breizhsport-server.git"
  sshPrivateKey: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACASMaIqBcbzFR619JtrOd29qn5VlDp/HCzAu4BmihMD2QAAAJjpwaFd6cGh
XQAAAAtzc2gtZWQyNTUxOQAAACASMaIqBcbzFR619JtrOd29qn5VlDp/HCzAu4BmihMD2Q
AAAEB8sH25/1I9GTTnwSP1YP0JHhWc8kOh5FACJ7XfHDe/hBIxoioFxvMVHrX0m2s53b2q
flWUOn8cLMC7gGaKEwPZAAAAFHRob21hQE1ZLVBDLUdBTUlORy0yAQ==
-----END OPENSSH PRIVATE KEY-----"
