postgres:
  version: "13.16"
  replicas: 2
  dbName: "Breizhsport"
  port: 5432
  user: "postgresUser"
  password: "1234"
  storage: "4Gi"
ingress:
  globalPort: 8080
express:
  replicas: 2
node: 
  version: "20-alpine"
  port: 3001
  env: "test"
api:
  githubLink: "git@github.com:Thomas-71/breizhsport-server.git"
  sshPrivateKey: "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBU01hSXFCY2J6RlI2MTlKdHJPZDI5cW41VmxEcC9IQ3pBdTRCbWloTUQyUUFBQUppSDFackZoOVdhCnhRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQVNNYUlxQmNiekZSNjE5SnRyT2QyOXFuNVZsRHAvSEN6QXU0Qm1paE1EMlEKQUFBRUI4c0gyNS8xSTlHVFRud1NQMVlQMEpIaFdjOGtPaDVGQUNKN1hmSERlL2hCSXhvaW9GeHZNVkhyWDBtMnM1M2IycQpmbFdVT244Y0xNQzdnR2FLRXdQWkFBQUFGSFJvYjIxaFFFMVpMVkJETFVkQlRVbE9SeTB5QVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0"
