apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-user-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: "{{ .Values.postgres.user.dbName }}"
  POSTGRES_USER: "{{ .Values.postgres.user.name }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.user.password }}"