apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres-user
          image: "postgres:{{ .Values.postgres.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.postgres.user.port }}
          envFrom:
            - configMapRef:
                name: postgres-user-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: storage-user-pvc