apiVersion: batch/v1
kind: Job
metadata:
  name: apply-schema-user
  namespace: argo-kube-test
spec:
  template:
    spec:
      containers:
      - name: apply-schema
        image: "postgres:{{ .Values.postgres.version }}"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: POSTGRES_PASSWORD
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            # Vérifier si la base de données existe déjà
            DB_EXISTS=$(psql -h {{ .Release.Name }}-user -U {{ .Values.postgres.user.name }} -p 5433 -d postgres -t -c "SELECT 1 FROM pg_database WHERE datname='{{ .Values.postgres.user.dbName }}';")
            if [ -z "$DB_EXISTS" ]; then
              # Créer la base de données si elle n'existe pas
              psql -h {{ .Release.Name }}-user -U {{ .Values.postgres.user.name }} -p 5433 -d postgres -c "CREATE DATABASE {{ .Values.postgres.user.dbName }};"
            fi
            # Appliquer le schéma SQL après la création
            psql -h {{ .Release.Name }}-user -U {{ .Values.postgres.user.name }} -p 5433 -d {{ .Values.postgres.user.dbName }} -f /schema/schema.sql
        volumeMounts:
        - name: schema-volume
          mountPath: /schema
      restartPolicy: Never
      volumes:
      - name: schema-volume
        configMap:
          name: postgre-user-schema
  backoffLimit: 3
