apiVersion: batch/v1
kind: Job
metadata:
  name: apply-schema-user
  namespace: argo-kube-test
spec:
  template:
    spec:
      containers:
      - name: apply-schema
        image: "postgres:{{ .Values.postgres.version }}"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: POSTGRES_PASSWORD
        command: ["/bin/sh", "-c"]
        args:
          - |
            DB_EXISTS=$(psql -h {{ .Release.Name }}-user -U {{ .Values.postgres.user.user }} -p 5433 -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='User'")
            if [ -z "$DB_EXISTS" ]; then
              psql -h {{ .Release.Name }}-user -U {{ .Values.postgres.user.user }} -p 5433 -d postgres -c "CREATE DATABASE \"User\""
            fi
            psql -h {{ .Release.Name }}-user -U {{ .Values.postgres.user.user }} -p 5433 -d User -f /schema/schema.sql
        volumeMounts:
        - name: schema-volume
          mountPath: /schema
      restartPolicy: Never
      volumes:
      - name: schema-volume
        configMap:
          name: postgre-user-schema
  backoffLimit: 3
