apiVersion: batch/v1
kind: Job
metadata:
  name: apply-schema-user
  namespace: argo-kube-test
spec:
  template:
    spec:
      containers:
      - name: apply-schema
        image: "postgres:{{ .Values.postgres.version }}"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: POSTGRES_PASSWORD
        command: ["psql"]
        args:
          - "-h"
          - {{ .Release.Name }}-user  # Nom du service pour User
          - "-U"
          - {{ .Values.postgres.user.user }}  # Nom d'utilisateur
          - "-d"
          - {{ .Values.postgres.user.dbName }}  # Nom de la base de données
          - "-p"
          - "5433"
          - "-f"
          - "/schema/schema.sql"
        volumeMounts:
        - name: schema-volume
          mountPath: /schema
      restartPolicy: Never
      volumes:
      - name: schema-volume
        configMap:
          name: postgre-user-schema
  backoffLimit: 3
