apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-user-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.user }}
  