apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-secret
  namespace: argo-kube-test
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.user.dbName | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.user.name | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.user.password | b64enc }}