apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-user
  ports:
    - name: db-port
      port: {{ .Values.postgres.user.port }}
      targetPort: 5432
