apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-breizhsport-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.breizhsport.storage }}
  