apiVersion: v1
kind: Secret
metadata:
  name: postgres-breizhsport-secret
  namespace: argo-kube-test
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.breizhsport.dbName | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.breizhsport.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.breizhsport.password | b64enc }}