apiVersion: batch/v1
kind: Job
metadata:
  name: apply-schema-job
  namespace: argo-kube-test
spec:
  template:
    spec:
      containers:
      - name: apply-schema
        image: "postgres:{{ .Values.postgres.version }}"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret 
              key: POSTGRES_PASSWORD
        command: ["/bin/sh", "-c"]
        args:
          args:
            - |
              echo "Listing databases..."
              psql -h {{ .Release.Name }}-database-internal-service -U {{ .Values.postgres.user }} -p {{ .Values.postgres.port }} -d postgres -c "\l"

              echo "Using database: {{ .Values.postgres.dbName }}"
              psql -h {{ .Release.Name }}-database-internal-service -U {{ .Values.postgres.user }} -p {{ .Values.postgres.port }} -d {{ .Values.postgres.dbName }} -c "\dt"

              echo "Applying schema..."
              psql -h {{ .Release.Name }}-database-internal-service -U {{ .Values.postgres.user }} -p {{ .Values.postgres.port }} -d {{ .Values.postgres.dbName }} -f /schema/schema.sql
        volumeMounts:
        - name: schema-volume
          mountPath: /schema
      restartPolicy: Never
      volumes:
      - name: schema-volume
        configMap:
          name: postgre-schema
  backoffLimit: 3
