apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - name: db-port
      port: {{ .Values.postgres.port }}
      targetPort: 5432