apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: argo-kube-test
spec:
  replicas: {{ .Values.express.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: api-container
          image: "node:{{ .Values.node.version }}"
          ports:
            - containerPort: {{ .Values.node.port }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"