apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: argo-kube-test
type: Opaque
data:
  API_PORT: {{ .Values.node.port | toString | b64enc }}
  NODE_ENV: {{ .Values.node.env | b64enc }}
  SSH_KEY: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBU01hSXFCY2J6RlI2MTlKdHJPZDI5cW41VmxEcC9IQ3pBdTRCbWloTUQyUUFBQUppSDFackZoOVdhCnhRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQVNNYUlxQmNiekZSNjE5SnRyT2QyOXFuNVZsRHAvSEN6QXU0Qm1paE1EMlEKQUFBRUI4c0gyNS8xSTlHVFRud1NQMVlQMEpIaFdjOGtPaDVGQUNKN1hmSERlL2hCSXhvaW9GeHZNVkhyWDBtMnM1M2IycQpmbFdVT244Y0xNQzdnR2FLRXdQWkFBQUFGSFJvYjIxaFFFMVpMVkJETFVkQlRVbE9SeTB5QVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=