apiVersion: v1
kind: Service
metadata:
  name: breizhsport-api
  namespace: argo-kube-test
spec:
  type: LoadBalancer
  selector:
    app: breizhsport-api
  ports:
    - port: {{ .Values.node.externalPort }}
      targetPort: {{ .Values.node.internalPort }}