apiVersion: v1
kind: Service
metadata:
  name: breizhsport-api
  namespace: argo-kube-test
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-api
  ports:
  - port: {{ .Values.node.serviceExternalPort }}     # Port exposé par le service (32000)
    targetPort: {{ .Values.node.podInternalPort }}   # Port où l'application écoute dans le pod (8080)