apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-secret
    labels:
      app: postgres
data:
  POSTGRES_DB: "{{ .Values.postgres.database.name }}"
  POSTGRES_USER: "{{ .Values.postgres.user.name }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.user.password }}"