apiVersion: batch/v1
kind: Job
metadata:
  name: apply-mysql-schema
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_HOST
          value: "mysql-service"  # Le nom de votre service MySQL
        - name: MYSQL_DATABASE
          value: "your_database_name"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        command: ["/bin/sh", "-c"]
        args:
          - |
            mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < /schema/schema.sql
        volumeMounts:
        - name: schema-volume
          mountPath: /schema
          subPath: schema.sql
      restartPolicy: OnFailure
      volumes:
      - name: schema-volume
        configMap:
          name: mysql-schema
          items:
          - key: schema.sql
            path: schema.sql
