apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-product-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.productStorage }}
  