apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-product-pvc
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.productStorage }}
  