apiVersion: v1
kind: Pod
metadata:
  name: postgres-product
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: "postgres:{{ .Values.postgres.version }}"
    env:
    - name: POSTGRES_PASSWORD
      value: {{ .Values.postgres.superUserPassword }}
    ports:
    - containerPort: {{ .Values.postgres.port }}
    volumeMounts:
    - name: schema-volume
      mountPath: /docker-entrypoint-initdb.d/schema.sql
      subPath: schema.sql
  volumes:
    - name: schema-volume
      configMap:
        name: postgres-schema
        items:
        - key: schema.sql
          path: schema.sql
    
