apiVersion: v1
kind: Pod
metadata:
  name: mysql-product
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: "mysql:{{ .Values.mysql.version }}"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: {{ .Values.mysql.rootPassword }}
    ports:
    - containerPort: {{ .Values.mysql.port }}
    volumeMounts:
    - name: schema-volume
      mountPath: /docker-entrypoint-initdb.d/schema.sql
      subPath: schema.sql
  volumes:
    - name: schema-volume
      configMap:
        name: mysql-schema
        items:
        - key: schema.sql
          path: schema.sql
    
