apiVersion: v1
kind: Pod
metadata:
  name: mysql-product
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: "mysql:{{ .Values.mysql.version }}"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: {{ .Values.mysql.rootPassword }}
    ports:
    - containerPort: {{ .Values.mysql.port }}
    volumeMounts:
    
