apiVersion: v1
kind: Pod
metadata:
  name: postgresql-product
  labels:
    app: postgresql
spec:
  containers:
  - name: postgresql
    image: "postgresql:{{ .Values.postgresql.version }}"
    env:
    - name: POSTGRES_ROOT_PASSWORD
      value: {{ .Values.postgresql.rootPassword }}
    ports:
    - containerPort: {{ .Values.postgresql.port }}
    volumeMounts:
    - name: schema-volume
      mountPath: /docker-entrypoint-initdb.d/schema.sql
      subPath: schema.sql
  volumes:
    - name: schema-volume
      configMap:
        name: postgresql-schema
        items:
        - key: schema.sql
          path: schema.sql
    
